"""init

Revision ID: 0673bb878aa7
Revises:
Create Date: 2026-06-11 13:32:22.809204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0673bb878aa7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'courses',
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('area', sa.String(length=50), nullable=False),
        sa.Column('tecnologies', sa.JSON(), nullable=False),
        sa.Column('link', sa.String(length=255), nullable=False),
        sa.Column('is_free', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.Date(),
            server_default=sa.text('(CURRENT_DATE)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.Date(),
            server_default=sa.text('(CURRENT_DATE)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('link'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'users',
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column(
            'role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False
        ),
        sa.Column('birth_date', sa.Date(), nullable=False),
        sa.Column('gender', sa.String(), nullable=False),
        sa.Column('educational_level', sa.String(), nullable=False),
        sa.Column('continent', sa.String(), nullable=False),
        sa.Column('country', sa.String(), nullable=False),
        sa.Column('state', sa.String(), nullable=True),
        sa.Column('city', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.Date(),
            server_default=sa.text('(CURRENT_DATE)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.Date(),
            server_default=sa.text('(CURRENT_DATE)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'health_checkins',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('mood', sa.String(length=50), nullable=False),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('context', sa.Text(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.Date(),
            server_default=sa.text('(CURRENT_DATE)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.Date(),
            server_default=sa.text('(CURRENT_DATE)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'professional_profiles',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('tech_area', sa.String(), nullable=False),
        sa.Column('experience_level', sa.String(), nullable=False),
        sa.Column('career_goal', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.Date(),
            server_default=sa.text('(CURRENT_DATE)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.Date(),
            server_default=sa.text('(CURRENT_DATE)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional_profiles')
    op.drop_table('health_checkins')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
