"""add tecnologies to professional db

Revision ID: 3e6ab77dfe60
Revises: 8b50cffb5a7b
Create Date: 2026-06-17 15:02:32.082889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6ab77dfe60'
down_revision: Union[str, Sequence[str], None] = '8b50cffb5a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_profiles', sa.Column('technologies', sa.ARRAY(sa.String()), nullable=True))
    op.execute("UPDATE professional_profiles SET technologies = '{}' WHERE technologies IS NULL")
    op.alter_column('professional_profiles', 'technologies', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional_profiles', 'technologies')
    # ### end Alembic commands ###
