"""change tecnologies to array

Revision ID: f0e9c0f1a698
Revises: 0673bb878aa7
Create Date: 2026-06-16 21:58:34.789984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0e9c0f1a698'
down_revision: Union[str, Sequence[str], None] = '0673bb878aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('health_checkins')
    op.drop_table('professional_profiles')
    
    op.alter_column('courses', 'tecnologies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               postgresql_using="translate(tecnologies::text, '[]', '{}')::varchar[]")  # ✅
    
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('courses', 'tecnologies',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('professional_profiles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tech_area', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('career_goal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('professional_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('professional_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('professional_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('health_checkins',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('health_checkins_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('health_checkins_pkey'))
    )
    # ### end Alembic commands ###
